# Generated by Django 3.2.5 on 2021-07-17 04:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False,
                                          primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('year_founded', models.IntegerField()),
                ('industry', models.CharField(max_length=255)),
                ('size_range', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=30)),
                ('linkedin_url', models.URLField(max_length=100)),
                ('current_employee_estimate', models.IntegerField()),
                ('total_employee_estimate', models.IntegerField()),
            ],
            options={
                'db_table': 'companies',
            },
        ),
    ]
