# Generated by Django 3.2.5 on 2021-07-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='year_founded',
            field=models.IntegerField(null=True),
        ),
    ]
