# Generated by Django 3.2.5 on 2021-07-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0002_alter_companies_year_founded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='locality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='size_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='year_founded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
