# Generated by Django 3.2.5 on 2021-07-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0005_alter_companies_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
